<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT2wpxcs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT2wpxcs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerT2wpxcs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerT2wpxcs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerT2wpxcs\appProdProjectContainer([
    'container.build_hash' => 'T2wpxcs',
    'container.build_id' => 'd1c68218',
    'container.build_time' => 1571657666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT2wpxcs');
