<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTmcn8eh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTmcn8eh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTmcn8eh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTmcn8eh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTmcn8eh\appDevDebugProjectContainer([
    'container.build_hash' => 'Tmcn8eh',
    'container.build_id' => '46a6dfaa',
    'container.build_time' => 1571758612,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTmcn8eh');
